# Generated by Django 4.2.1 on 2023-05-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_title_id', models.IntegerField()),
                ('original_title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('date_published', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('reviews_from_users', models.IntegerField()),
                ('reviews_from_critics', models.IntegerField()),
            ],
        ),
    ]
