# Generated by Django 4.2.1 on 2023-05-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='imdb',
            name='imdb_title_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
